name = "backend-bsca"
compatibility_date = "2024-09-15"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "KV"
id = "8f2663c7208140a098966080234d6704"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "d1-bsca"
database_id = "be549d2f-f47f-46f3-8179-dbbf247fac16"

# [ai]
# binding = "AI"
